os: osx
language: generic
cache:
  timeout: 1000
  directories:
  - "$HOME/.cabal/"
branches:
  only:
  - /rc\/.*/
install:
- set -e
- ulimit -n 4096
- brew install ghc
- brew install cabal-install
- cabal --version
- ghc --version
- cabal v2-update
- |
  export VERSION=$(grep '^[Vv]ersion:' pandoc.cabal | awk '{print $$2;}')
  export BASEDIR=$(pwd)
  export ARTIFACTS=${BASEDIR}/macos-release-candidate
  export RESOURCES=${ARTIFACTS}/Resources
  export ROOT=${ARTIFACTS}/pandoc
  export DEST=${ROOT}/usr/local
  export ME=$(whoami)
  export BASE=pandoc-$VERSION
  mkdir -p ${ARTIFACTS}
  mkdir -p ${RESOURCES}
  mkdir -p ${DEST}/bin
  mkdir -p ${DEST}/share/man/man1
  cabal v2-configure --enable-tests -f-export-dynamic -fstatic -fembed_data_files --enable-executable-static --ghc-options '-optc-Os -optl=-pthread' pandoc
  cabal v2-build
  cabal v2-test -j1
  cabal v2-install --install-method=copy --installdir=.
  cp pandoc ${DEST}/bin
  strip ${DEST}/bin/pandoc
  cp man/pandoc.1 ${DEST}/share/man/man1/pandoc.1
  ${DEST}/bin/pandoc -t html5 -s COPYING.md -Vpagetitle=License \
    -o ${RESOURCES}/license.html
  chown -R $ME:staff ${ROOT}
  sed -e "s/PANDOCVERSION/${VERSION}/" macos/distribution.xml.in > ${ARTIFACTS}/distribution.xml
  cp macos/Makefile ${ARTIFACTS}/
  echo ${VERSION} > ${ARTIFACTS}/version.txt
deploy:
  on:
    all_branches: true
  provider: s3
  bucket: travis-jgm-pandoc
  region: us-west-1
  edge: true
  local_dir: macos-release-candidate
  access_key_id:
    secure: ohEst8EP8Z3r/bPMlYgPATo3B/ye48Z0aGp4W1pEhDZjqufLUVTFBIoicvPApCkTrbKMNTdG+KmasrO/leHpju0uFKYQHDtJmHZe3avIOIdbGnOqn97+mmLZBN5skiJWNtrxnN/TuAM+wlePz1dQpohPt6J3S70ct8DsOdZOaGI=
  secret_access_key:
    secure: qZ2RN4Bx4WRcVz9H8ae4S6a3AA85kcca0RdMimIREdGSx4ewMYa8lSdcKDvRbPwXRy8H3SeviqL2tTZw3+ej1jccAHowMj8Zvde5EJwX0+qO4Sr0zdWjnsvMeUmx9pO1oL3L/09KTWiMTT+d4XNpE8eqiY08qN8oMj0EPeR/AS4=
